apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-backend
spec:
  replicas: 1
  stratergy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: ecommerce-backend
  template:
    metadata:
      labels:
        app: ecommerce-backend
    spec:
      containers:
        - name: ecommerce-backend
          image: ankitdawra/ecommerce-backend:IMAGE_TAG
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
        - name: product-microservice
          image: ankitdawra/product-microservice:IMAGE_TAG
          imagePullPolicy: Always
          ports:
            - containerPort: 6000
---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-backend-service
spec:
  selector:
    app: ecommerce-backend
  ports:
    - port: 5000
      targetPort: 5000
  type: LoadBalancer
